pipeline {
	environment {
		SAG_HOME="C:/SoftwareAG912"
	}
	
	agent any
	
	stages {
		stage('startup: get variables') {
			steps{
				print "AAAAAAAAAA"
			}		
		}
		
		stage('startup: set variables') {
			steps{
				print "BBBBBBBBBBBB"
			}		
		}		
	}
	
	post {
		always {
			cleanWs()
		}
	}


}